name: Build and Push Angular Docker Image

on:
  push:
    branches:
      - main  # Déclenche sur chaque push dans la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code du repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer Node.js (pour builder Angular)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Mets la version que tu utilises localement si différente

      # Étape 3 : Installer les dépendances npm
      - name: Install dependencies
        run: npm install

      # Étape 4 : Build Angular en mode production
      - name: Build Angular app
        run: npm run build --prod

      # Étape 5 : Configurer Docker Buildx (pour construire les images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 6 : Se connecter à Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 7 : Construire et pousser l’image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile  # Assure-toi que ton Dockerfile est à la racine
          push: true
          tags: ranimbouzidi/angular-app:latest
